title: TABConf 2023
logo: /assets/img/nogood/512x512/NG_Stickers_Keys_Color.png
description: A Technical Bitcoin Conference
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
